import './globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { ToasterProvider } from '@/shared/providers/toaster-provider';
import { TooltipProvider } from '@/shared/providers/tooltip-provider';

const inter = Inter({
  variable: '--font-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <TooltipProvider>{children}</TooltipProvider>
        <ToasterProvider />
      </body>
    </html>
  );
}
